esphome:
  name: "nasa00"

esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'MyPassword'
  encryption:
    key: "xIAK2/wrGPQJHQinpI/rx7NW+5ZDJu6f8LQDX4qV0KM="

ota:
  password: "0e6fa19a9f5b70b9e2dd9630eadf82a7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nasa0 Fallback Hotspot"
    password: "CJKHtyiGuGS6"

captive_portal:
    
# Example configuration entry
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1600x1200

  # Image settings
  name: NASA0

# Example configuration entry for camera webserver
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
    
# Example configuration entry
light:
  - platform: binary
    name: "Flash"
    output: light_output
    restore_mode: ALWAYS_OFF

output:
  - id: light_output
    platform: gpio
    pin: GPIO04